"""add model_file_path and scan file_path

Revision ID: 29009b56b1eb
Revises: 5f0fe978e02e
Create Date: 2026-03-15 20:26:02.369019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29009b56b1eb'
down_revision = '5f0fe978e02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pad_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_file_path', sa.String(length=512), nullable=True))

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    with op.batch_alter_table('pad_models', schema=None) as batch_op:
        batch_op.drop_column('model_file_path')

    # ### end Alembic commands ###
